/* ARCH prototype: the repository documents shown in Browse, Search Results and Document Detail
   (detail.html?doc=<id>). All entries except "cidr-2025" are imaginary sample studies.
   The ones marked "RRL" are based on the related studies reviewed in the Group 4 capstone
   manuscript (institutional repositories, open access, metadata, digitization, preservation).
   Demo only: every document opens the same PDF (the Group 4 capstone manuscript, "cidr-2025"),
   so the viewer can be shown for any title. Only "cidr-2025" matches that PDF.
   The college of each document comes from its department (see js/colleges.js). */
(function () {
  var PDF = "cidr-2025";
  var LIST = [
    { id: "cidr-2025", title: "A Web-Based Centralized Institutional Digital Repository for Academic Research Management at Holy Angel University",
      type: "Capstone Project", year: "2026", department: "Information Technology",
      authors: "Sarmiento, Adrian P.; Sicat, Kurt Justine T.; Tienzo, Krisean G.; Villanueva, Martin Conrad S.",
      keywords: "Institutional repository; Research management; Dublin Core; Knimbus SSO",
      abstract: "The University Research Office (URO) of Holy Angel University currently manages the submission, evaluation, and storage of academic research outputs — including faculty research papers, undergraduate theses, and capstone projects — through an email-based process with documents stored in a restricted SharePoint repository. This manual, email-driven workflow limits centralized tracking of submission status and prevents students, faculty, and other members of the HAU community from directly searching or accessing approved research outputs. This study proposes the development of a Web-Based Centralized Institutional Digital Repository for Academic Research Management, a web-based application built using React, Supabase (PostgreSQL), and Knimbus single sign-on (SSO) authentication. The proposed system provides three levels of role-based access — administrative personnel, authorized uploaders, and general authorized users — supporting a structured document submission and approval workflow, Dublin Core metadata-based cataloging, multi-criteria search and filtering, and in-browser document viewing. The system was developed following the Prototyping Model, allowing iterative refinement based on feedback from the URO and target users. To evaluate the proposed system, a total of 364 participants — 361 end-users (URO staff, thesis instructors and coordinators, faculty members, and students with research involvement) selected through purposive and proportional stratified sampling, and 3 IT experts selected through expert sampling — took part in usability testing and technical evaluation. End-user perceptions of usability were measured using the System Usability Scale (SUS), while IT experts evaluated the system's technical quality using an ISO/IEC 25010-based instrument across five quality characteristics: Functional Suitability, Usability, Reliability, Performance Efficiency, and Security. Findings from this evaluation are intended to determine the system's readiness to support centralized, secure, and accessible research output management at Holy Angel University." },

    /* ---- Based on the manuscript's RRL ---- */
    { id: "self-archiving", title: "Faculty Self-Archiving Practices and Barriers to Institutional Repository Deposit in a Private University in Central Luzon",
      type: "Faculty Research", year: "2024", department: "Information Systems",
      authors: "Lacson, Maricel D.; Guevarra, Noel P.", keywords: "Self-archiving; Faculty deposit; Institutional repository; Open access",
      abstract: "Following Kim (2007) and Rifai (2023), who found that faculty rarely deposit their work voluntarily, this study surveyed 212 HAU faculty members about how they store and share their research. Most kept papers on personal drives or email; the main barriers were copyright uncertainty, lack of time, and not knowing a repository existed. Respondents said a simple deposit form and URO-mediated uploading would make them more likely to deposit." },
    { id: "open-access", title: "Awareness and Use of Open Access Resources Among Undergraduate Researchers of Holy Angel University",
      type: "Thesis", year: "2023", department: "Communication",
      authors: "Dizon, Alyssa Mae R.; Mallari, Joshua T.; Pangilinan, Erika S.", keywords: "Open access; Information literacy; Undergraduate research; Green open access",
      abstract: "Drawing on Harnad et al. (2008) and the open access movement, this thesis measured how aware 384 HAU undergraduates in thesis and capstone courses are of open access journals and repositories. Awareness was high for Google Scholar but low for repositories such as DOAJ and institutional repositories. Students who had attended a library orientation used open access sources significantly more often." },
    { id: "dublin-core", title: "A Dublin Core Metadata Application Profile for Undergraduate Theses and Capstone Projects",
      type: "Capstone Project", year: "2025", department: "Information Systems",
      authors: "Ocampo, Rhea Joy L.; Santos, Miguel A.; Tuazon, Carlo B.", keywords: "Dublin Core; Metadata; Cataloging; Application profile",
      abstract: "This capstone project defines a Dublin Core-based metadata profile for HAU student research, covering fifteen core elements plus local fields for adviser, panel, and research agenda theme. The profile was tested by cataloging 150 sample theses; two librarians rated it complete and easy to apply, and it reduced cataloging time compared with free-form spreadsheets." },
    { id: "dspace-eprints", title: "Comparative Evaluation of DSpace and EPrints for a Mid-Sized Philippine University Library",
      type: "Capstone Project", year: "2019", department: "Information Technology",
      authors: "Yumul, Kevin R.; Bondoc, Patricia Ann M.", keywords: "DSpace; EPrints; Open-source repository software; Evaluation",
      abstract: "Extending Castagné's (2013) environmental scan of repository platforms, this project installed DSpace and EPrints on identical servers and compared them on installation effort, metadata support, search, access control, and maintenance. DSpace scored higher on metadata and access control, while EPrints was easier to set up and customize. The study recommends a custom system where local workflows, such as research office approval, matter most." },
    { id: "digitization", title: "Digitization of Legacy Printed Theses in Philippine Academic Libraries: Status, Costs, and Priorities",
      type: "Faculty Research", year: "2022", department: "Information Technology",
      authors: "Tiglao, Rosalinda C.", keywords: "Digitization; Academic libraries; Legacy theses; Philippines",
      abstract: "Building on Lagas and Isip (2023) and Esposo-Betan and Fresnido (2022), this study surveyed 28 academic libraries in Central Luzon on the digitization of printed theses. Only 18% had digitized more than half of their collection; limited budget, staff, and scanning equipment were the main obstacles. The paper proposes a priority scheme that digitizes the most requested and most fragile titles first." },
    { id: "preservation", title: "Digital Preservation Practices for Born-Digital Research Outputs in Philippine Higher Education Institutions",
      type: "Faculty Research", year: "2020", department: "Information Systems",
      authors: "Manalang, Joseph E.; Serrano, Ma. Theresa G.", keywords: "Digital preservation; Born-digital records; File formats; Backup",
      abstract: "Guided by the preservation issues synthesized by Asadi et al. (2019), this study interviewed IT and library staff from 12 Philippine HEIs. Most stored research files without checksums, format migration plans, or off-site backups. The authors recommend PDF/A as the preservation format and a simple three-copy backup policy for institutional repositories." },
    { id: "deposit-policy", title: "Mandatory Deposit Policies and the Visibility of Research Outputs in Selected Philippine Universities",
      type: "Dissertation", year: "2023", department: "Secondary Education",
      authors: "Canlas, Evelyn M.", keywords: "Mandatory deposit; Research policy; Research visibility; Higher education",
      abstract: "This dissertation compares universities that require deposit of theses and faculty research with those that rely on voluntary deposit, following the concerns raised by Pinfield et al. (2014) and Imoro and Saurombe (2024). Institutions with a mandatory, office-mediated deposit policy had repositories four times larger and more frequently cited outputs. A model policy for Catholic private universities is proposed." },
    { id: "knowledge-mgmt", title: "Knowledge Management Practices and Research Productivity of Faculty in Private Higher Education Institutions in Pampanga",
      type: "Faculty Research", year: "2021", department: "Human Resource Management",
      authors: "Fernandez, Liza B.; David, Ronaldo S.", keywords: "Knowledge management; Research productivity; Faculty; Private HEIs",
      abstract: "Informed by Fujita et al.'s (2022) review of knowledge management and repositories, this study surveyed 305 faculty members from six private HEIs. Knowledge sharing and knowledge storage practices significantly predicted the number of papers published and presented. Centralized storage of research outputs was the practice faculty rated as most lacking." },
    { id: "proposal-tracker", title: "A Web-Based Research Proposal Tracking System for a University Research Office",
      type: "Capstone Project", year: "2023", department: "Information Technology",
      authors: "Lingat, Mark Joseph C.; Sunga, Andrea Nicole P.; Timbang, Ralph V.", keywords: "Research management system; Proposal tracking; Workflow; Web application",
      abstract: "Similar to the research management system of Celis and Lagda (2025) and the document management system of Alade (2023), this project replaces email-based proposal routing with a web system where faculty submit proposals and research office staff record review decisions. In user acceptance testing, processing time per proposal dropped and every proposal's status became visible to its author." },
    { id: "bibliometric", title: "A Bibliometric Profile of Holy Angel University Research Outputs, 2010–2020",
      type: "Faculty Research", year: "2021", department: "Computer Science",
      authors: "Garcia, Benedict T.; Mercado, Joanna L.", keywords: "Bibliometrics; Research output; Citation analysis; Scopus",
      abstract: "Using methods similar to Bashir et al. (2022) and Rojas et al. (2025), this study analyzed 486 publications affiliated with HAU from 2010 to 2020. Output grew steadily after 2015, led by engineering, computing, and business. Most papers appeared in local journals, and fewer than a third had any online full-text copy, pointing to the need for an institutional repository." },
    { id: "opac-sus", title: "Usability of University Library Online Public Access Catalogs Measured with the System Usability Scale",
      type: "Thesis", year: "2018", department: "Information Systems",
      authors: "Aquino, Janella P.; Rivera, Christian Paul D.", keywords: "OPAC; Usability; System Usability Scale; Library systems",
      abstract: "This thesis asked 150 students to complete search tasks on three university library catalogs and rate them with the System Usability Scale. Average scores ranged from 54 to 71, and the lowest-rated catalog lacked filters by college and year. The findings informed later work on searchable research repositories." },
    { id: "rbac", title: "Role-Based Access Control for Restricted Research Documents in Academic Repositories",
      type: "Capstone Project", year: "2024", department: "Computer Science",
      authors: "Salas, Dominic A.; Cortez, Francine M.; Lopez, Nathaniel G.", keywords: "Role-based access control; Document security; Institutional repository; Watermarking",
      abstract: "This capstone project designs a role-based access model for a university repository where abstracts are public but full texts need approval. It adds request-and-approve access, time-limited viewing, and on-screen watermarks. Penetration tests by three IT experts found no way to download restricted files without approval." },
    { id: "teacher-sharing", title: "Teachers' Readiness to Share Instructional Research Through Open Repositories",
      type: "Dissertation", year: "2021", department: "Secondary Education",
      authors: "Pamintuan, Ma. Cecilia R.", keywords: "Open educational resources; Teacher research; Repository adoption; Action research",
      abstract: "This dissertation surveyed 420 basic education teachers in Pampanga about sharing their action research through open repositories. Teachers valued sharing but feared plagiarism and did not know how to license their work. A training module on repository deposit and Creative Commons licensing improved readiness scores significantly." },

    /* ---- School of Computing ---- */
    { id: "enroll", title: "Design and Implementation of a Web-Based Enrollment Analytics Dashboard for Higher Education Institutions",
      type: "Capstone Project", year: "2025", department: "Information Technology",
      authors: "Dela Cruz, Juan P.; Santos, Maria L.", keywords: "Enrollment; Analytics; Higher education; Dashboard",
      abstract: "This capstone project develops a dashboard that helps registrars monitor enrollment trends and forecast section demand." },
    { id: "jeepney", title: "JeepRoute: A Mobile Application for Jeepney Route Navigation in Angeles City",
      type: "Capstone Project", year: "2019", department: "Information Technology",
      authors: "Sicat, Ramon Jr. L.; Castro, Diane M.", keywords: "Mobile application; Public transport; Route finding; Angeles City",
      abstract: "JeepRoute maps 21 jeepney routes in Angeles City and suggests the fewest-transfer trip between two points. Commuters who tested it rated it highly for accuracy, though they asked for fare estimates and offline maps." },
    { id: "sentiment", title: "Sentiment Analysis of Kapampangan and Code-Switched Social Media Posts Using Transformer Models",
      type: "Thesis", year: "2024", department: "Computer Science",
      authors: "Dayrit, Ethan G.; Nunag, Samantha Rose P.", keywords: "Sentiment analysis; Kapampangan; Natural language processing; Code-switching",
      abstract: "This thesis builds a labeled dataset of 6,000 Kapampangan, English, and Filipino code-switched posts and fine-tunes a multilingual transformer to classify sentiment. The model reached 81% accuracy, well above a keyword baseline." },
    { id: "history-game", title: "Bayani: An Educational Adventure Game on Philippine Revolutionary History",
      type: "Capstone Project", year: "2023", department: "Entertainment and Multimedia Computing",
      authors: "Tolentino, Aaron James B.; Gomez, Hannah L.", keywords: "Educational game; Philippine history; Game-based learning; Unity",
      abstract: "Bayani is a 2D adventure game for Grade 6 pupils covering the 1896 Philippine Revolution. In a pilot with two classes, pupils who played the game scored higher on a history quiz than pupils taught through lecture alone." },

    /* ---- School of Business and Accountancy ---- */
    { id: "finlit", title: "Financial Literacy and Small Enterprise Sustainability in Pampanga",
      type: "Faculty Research", year: "2023", department: "Business Administration",
      authors: "Bautista, Erlinda M.", keywords: "Financial literacy; Small enterprises; Sustainability",
      abstract: "This study examines how financial literacy relates to the long-term survival of micro and small enterprises." },
    { id: "bsba", title: "Employability of BSBA Graduates of HAU, Batch 2023",
      type: "Thesis", year: "2024", department: "Business Administration",
      authors: "Reyes, Mark Anthony L.; Cruz, Jenny R.", keywords: "Employability; Graduate tracer; Business administration",
      abstract: "A tracer study of HAU's 2023 BSBA graduates, looking at how quickly they found work and how well their jobs match their degree." },
    { id: "ofw", title: "Financial Resilience of OFW Families in Pampanga",
      type: "Faculty Research", year: "2026", department: "Accountancy",
      authors: "Sarmiento, Adrian P.", keywords: "OFW families; Financial resilience; Remittances",
      abstract: "This study looks at how families of overseas Filipino workers in Pampanga manage remittances and prepare for financial shocks." },
    { id: "socmed", title: "Social Media Marketing Practices of Small Food Businesses in Angeles City",
      type: "Thesis", year: "2026", department: "Marketing Management",
      authors: "Tan, Bianca L.; Mercado, John Carlo P.", keywords: "Social media marketing; Food businesses; MSMEs",
      abstract: "This thesis describes how small food businesses in Angeles City use social media to reach customers and which practices relate to higher sales." },
    { id: "ewallet", title: "E-Wallet Adoption Among Sari-Sari Store Owners in Mabalacat City",
      type: "Thesis", year: "2022", department: "Financial Management",
      authors: "Lugtu, Kimberly Anne S.; Pineda, Jericho M.", keywords: "E-wallets; Digital payments; Sari-sari stores; Technology acceptance",
      abstract: "Using the Technology Acceptance Model, this thesis surveyed 260 sari-sari store owners. Perceived usefulness and customer demand drove adoption, while fear of transaction fees and scams held owners back." },
    { id: "tax-compliance", title: "Tax Compliance of Freelance Online Workers in Central Luzon",
      type: "Thesis", year: "2012", department: "Accountancy",
      authors: "Galang, Rowena T.; Soriano, Michael B.", keywords: "Tax compliance; Freelancers; Online work; BIR registration",
      abstract: "This thesis found that most freelance online workers surveyed were not registered with the BIR, mainly because they did not know they had to be. Simpler registration and online filing were the changes they said would help most." },

    /* ---- School of Engineering and Architecture ---- */
    { id: "seismic", title: "Seismic Performance of Low-Rise Reinforced Concrete Buildings in Central Luzon",
      type: "Thesis", year: "2024", department: "Civil Engineering",
      authors: "Mendoza, Rafael T.; Villanueva, Carla S.", keywords: "Seismic performance; Reinforced concrete; Central Luzon",
      abstract: "This thesis assesses how typical low-rise reinforced concrete buildings in Central Luzon would perform during a strong earthquake." },
    { id: "uav-wing", title: "Wind Tunnel Testing of a Low-Cost UAV Wing Profile for Agricultural Spraying",
      type: "Thesis", year: "2021", department: "Aeronautical Engineering",
      authors: "Manansala, Jerome P.; Quiambao, Denise R.; Lansangan, Paul A.", keywords: "UAV; Airfoil; Wind tunnel; Agricultural drones",
      abstract: "The team built and tested three wing profiles for a spraying drone in the HAU wind tunnel. A modified NACA 4412 profile gave the best lift-to-drag ratio at the low speeds used for spraying rice fields." },
    { id: "heritage-reuse", title: "Adaptive Reuse of Heritage Houses in the Santo Rosario District of Angeles City",
      type: "Thesis", year: "2016", department: "Architecture",
      authors: "Henson, Patricia Mae L.", keywords: "Adaptive reuse; Heritage conservation; Angeles City; Architecture",
      abstract: "This thesis documents 14 heritage houses near the Holy Rosary Parish and proposes new uses, such as cafés and museums, that keep their original features while making them financially sustainable." },
    { id: "smart-irrigation", title: "Solar-Powered IoT Irrigation Controller for Small Rice Farms in Pampanga",
      type: "Capstone Project", year: "2022", department: "Electronics Engineering",
      authors: "Gozum, Adrian C.; Musni, Kathleen B.; Tayag, Vincent R.", keywords: "IoT; Irrigation; Solar power; Soil moisture",
      abstract: "The project built a solar-powered controller that opens irrigation pumps based on soil moisture readings and sends alerts by SMS. Field tests on a one-hectare farm cut pump running time by 32%." },
    { id: "ergonomics", title: "Ergonomic Assessment of Sewing Workstations in Clark Freeport Garment Factories",
      type: "Thesis", year: "2013", department: "Industrial Engineering",
      authors: "Dela Pena, Maricar S.; Bognot, Raymond T.", keywords: "Ergonomics; RULA; Garment industry; Workstation design",
      abstract: "Using RULA scores and a body discomfort survey, this thesis found high musculoskeletal risk among sewers. Adjustable chairs and tilted work surfaces reduced reported discomfort in a four-week trial." },

    /* ---- School of Arts and Sciences ---- */
    { id: "weaving", title: "Traditional Kapampangan Weaving Techniques: A Documentation",
      type: "Faculty Research", year: "2025", department: "Communication",
      authors: "Pineda, Lourdes M.", keywords: "Kapampangan culture; Weaving; Documentation",
      abstract: "This study documents the materials, patterns and steps used by Kapampangan weavers, based on interviews and field observation." },
    { id: "radio-language", title: "Use of the Kapampangan Language in Local AM and FM Radio Programs",
      type: "Thesis", year: "2011", department: "Communication",
      authors: "Tongol, Leah Marie C.; Yabut, Christopher D.", keywords: "Kapampangan language; Radio; Language maintenance; Media",
      abstract: "This thesis recorded 60 hours of local radio and found that Kapampangan was used in only a quarter of airtime, mostly in news and public service programs. Station managers cited audience ratings and advertiser demand as reasons for using Filipino and English." },
    { id: "academic-pressure", title: "Parental Academic Pressure and Test Anxiety Among Senior High School Students",
      type: "Thesis", year: "2023", department: "Psychology",
      authors: "Sampang, Nicole Anne G.; Lim, Justin Carl R.", keywords: "Academic pressure; Test anxiety; Adolescents; Parenting",
      abstract: "A correlational study of 318 senior high school students found a moderate positive link between perceived parental pressure and test anxiety, which was weaker for students with strong peer support." },
    { id: "seafarer-spouses", title: "Psychological Well-Being of Spouses of Filipino Seafarers",
      type: "Dissertation", year: "2009", department: "Psychology",
      authors: "Bernardo, Imelda S.", keywords: "Psychological well-being; Seafarers; Family separation; Coping",
      abstract: "This dissertation interviewed and surveyed spouses of seafarers in Pampanga. Well-being was lowest during the first months of each contract and highest among spouses active in church and community groups." },

    /* ---- School of Education ---- */
    { id: "teacher", title: "Teacher Digital Competence and Student Engagement in Blended Classrooms",
      type: "Dissertation", year: "2022", department: "Secondary Education",
      authors: "Tolentino, Grace A.", keywords: "Digital competence; Student engagement; Blended learning",
      abstract: "A mixed-methods dissertation on how teacher digital skills shape student engagement in blended learning." },
    { id: "mtb-mle", title: "Mother Tongue-Based Instruction and Early Reading Skills of Kapampangan-Speaking Grade 1 Pupils",
      type: "Thesis", year: "2015", department: "Elementary Education",
      authors: "Simbulan, Kristine Joy A.; Dabu, Ericka M.", keywords: "MTB-MLE; Early reading; Kapampangan; Grade 1",
      abstract: "Pupils taught to read first in Kapampangan scored higher in phonemic awareness and word reading at the end of Grade 1 than pupils taught in Filipino, according to this quasi-experimental thesis." },
    { id: "gamified-math", title: "Gamified Online Quizzes and Mathematics Achievement of Grade 8 Students",
      type: "Thesis", year: "2020", department: "Secondary Education",
      authors: "Cunanan, Mark Kevin S.; Garcia, Ella Mae T.", keywords: "Gamification; Mathematics achievement; Online quizzes; Junior high school",
      abstract: "Two Grade 8 sections used either gamified online quizzes or paper quizzes for one quarter. The gamified group had higher post-test scores and reported more enjoyment of mathematics." },

    /* ---- School of Hospitality and Tourism Management ---- */
    { id: "sisig-trail", title: "Culinary Tourism Potential of Pampanga's Sisig Trail",
      type: "Thesis", year: "2018", department: "Tourism Management",
      authors: "Pangan, Arvin J.; Macapagal, Sheila R.", keywords: "Culinary tourism; Sisig; Destination development; Pampanga",
      abstract: "This thesis mapped 17 sisig restaurants in Angeles City and surveyed 250 visitors. Food was the main reason for most visits, and respondents wanted a guided trail with maps, stories, and tasting passes." },
    { id: "hotel-service", title: "Service Quality and Guest Loyalty in Mid-Range Hotels in Clark Freeport Zone",
      type: "Thesis", year: "2021", department: "Hospitality Management",
      authors: "Serrano, Jasmine P.; David, Angelo M.", keywords: "Service quality; SERVQUAL; Guest loyalty; Hotels",
      abstract: "Using the SERVQUAL model, this thesis found that responsiveness and reliability most strongly predicted whether guests intended to return to mid-range hotels in Clark." },
    { id: "green-resorts", title: "Sustainable Practices of Small Resorts in Zambales and Their Effect on Guest Choice",
      type: "Faculty Research", year: "2010", department: "Hospitality Management",
      authors: "Gutierrez, Carmela V.", keywords: "Sustainable tourism; Green practices; Resorts; Guest choice",
      abstract: "This study surveyed 22 small resorts and 400 guests. Few resorts had written sustainability policies, but guests were willing to pay slightly more for resorts that reduced plastic and conserved water." },

    /* ---- School of Nursing and Allied Medical Sciences ---- */
    { id: "nursing", title: "Effects of Simulation-Based Learning on the Clinical Competence of Nursing Students",
      type: "Thesis", year: "2024", department: "Nursing",
      authors: "Garcia, Angelica R.", keywords: "Simulation-based learning; Clinical competence; Nursing education",
      abstract: "This thesis compares the clinical competence of nursing students trained with high-fidelity simulation against those trained through traditional return demonstration." },
    { id: "dengue-bhw", title: "Knowledge and Practices of Barangay Health Workers on Dengue Prevention in Angeles City",
      type: "Thesis", year: "2019", department: "Nursing",
      authors: "Ignacio, Rachelle A.; Manalo, Daniel J.; Tuazon, Kate M.", keywords: "Dengue; Barangay health workers; Health education; Prevention",
      abstract: "Barangay health workers knew dengue symptoms well but often missed breeding sites such as tires and roof gutters. The thesis proposes a short training guide with a household checklist." },
    { id: "anemia", title: "Prevalence of Iron-Deficiency Anemia Among Female College Students",
      type: "Thesis", year: "2017", department: "Medical Technology",
      authors: "Salenga, Joanna Marie P.; Vergara, Trisha L.", keywords: "Anemia; Hemoglobin; Female students; Nutrition",
      abstract: "Blood samples from 180 female students showed a 21% prevalence of iron-deficiency anemia, higher among students who skipped breakfast or followed restrictive diets." },
    { id: "radiation-safety", title: "Radiation Safety Awareness Among Radiologic Technology Interns in Pampanga Hospitals",
      type: "Thesis", year: "2022", department: "Radiologic Technology",
      authors: "Mangune, Ralph Edward C.; Pineda, Arianne S.", keywords: "Radiation safety; ALARA; Interns; Radiologic technology",
      abstract: "Interns scored well on ALARA principles but often skipped dosimeter use and lead shielding during busy shifts. The thesis recommends pre-internship refresher sessions and supervisor checklists." },
    { id: "nurse-retention", title: "Transformational Leadership of Nurse Managers and Staff Nurse Retention in Central Luzon Hospitals",
      type: "Dissertation", year: "2018", department: "Nursing",
      authors: "Manaloto, Rosario G.", keywords: "Transformational leadership; Nurse retention; Turnover intention; Hospitals",
      abstract: "This dissertation surveyed 540 staff nurses in 11 hospitals. Nurses who rated their managers high in transformational leadership were far less likely to plan to leave, even when pay was held constant." },

    /* ---- College of Criminal Justice Education and Forensics ---- */
    { id: "police-visibility", title: "Community Perception of Police Visibility and Feelings of Safety in Angeles City",
      type: "Thesis", year: "2020", department: "Criminology",
      authors: "Dimarucut, Jayson R.; Laxamana, Kristel P.", keywords: "Police visibility; Community policing; Fear of crime; Public safety",
      abstract: "Residents of six barangays who saw foot patrols at least weekly reported feeling safer at night. The thesis recommends regular foot patrols and barangay assemblies with local police." },
    { id: "fingerprint-wet", title: "Development of Latent Fingerprints on Wet Non-Porous Surfaces Using Low-Cost Powders",
      type: "Thesis", year: "2025", department: "Forensic Science",
      authors: "Baluyut, Angela Mae C.; Santos, Rodel F.", keywords: "Latent fingerprints; Powder method; Wet surfaces; Forensic science",
      abstract: "Charcoal and cornstarch-based powders were compared with commercial powder on glass and plastic soaked in water. A charcoal-cornstarch mix developed usable prints on 70% of samples, close to the commercial product." },

    /* ---- HAU Aviation Institute ---- */
    { id: "clark-terminal", title: "Passenger Satisfaction with the New Passenger Terminal Building of Clark International Airport",
      type: "Thesis", year: "2026", department: "Aviation Management",
      authors: "Calma, Jeremiah S.; Yalung, Bea Patricia D.", keywords: "Passenger satisfaction; Airport service quality; Clark International Airport; Aviation",
      abstract: "A survey of 400 departing passengers rated cleanliness and design highest, and wayfinding and food prices lowest. The thesis proposes clearer signage and a mobile wayfinding guide." },
    { id: "turnaround", title: "Causes of Ground Handling Turnaround Delays for Low-Cost Carriers at Clark",
      type: "Faculty Research", year: "2025", department: "Aviation Management",
      authors: "Navarro, Eduardo P.", keywords: "Ground handling; Turnaround time; Low-cost carriers; Airport operations",
      abstract: "Observation of 120 turnarounds showed that late baggage loading and fueling queues caused most delays. Staggered fueling schedules were estimated to cut average turnaround time by seven minutes." },

    /* ---- Basic Education ---- */
    { id: "screen-time", title: "Screen Time and Sleep Quality of Grade 6 Pupils",
      type: "Faculty Research", year: "2022", department: "Grade School",
      authors: "Musni, Liezel A.; Tiongco, Arnel P.", keywords: "Screen time; Sleep quality; Children; Gadget use",
      abstract: "Pupils who used gadgets for more than three hours a day on school days slept about 50 minutes less and reported more daytime sleepiness. The study recommends a family media plan for parents." },
    { id: "rice-husk-filter", title: "Rice Husk Ash as a Low-Cost Water Filter Medium for Household Use",
      type: "Capstone Project", year: "2024", department: "Senior High School (STEM)",
      authors: "Dela Cruz, Andrei M.; Lapid, Francine S.; Yambao, Nathaniel J.", keywords: "Water filtration; Rice husk ash; Turbidity; Low-cost technology",
      abstract: "A filter layering sand, gravel, and rice husk ash reduced the turbidity of well water by 87%, close to a commercial filter at a fraction of the cost." },
    { id: "abm-savings", title: "Saving Habits and Financial Literacy of ABM Students",
      type: "Capstone Project", year: "2019", department: "Senior High School (ABM)",
      authors: "Sangalang, Bea Nicole R.; Castro, Jomar P.", keywords: "Saving habits; Financial literacy; Senior high school; Allowance",
      abstract: "Students with higher financial literacy scores saved a larger share of their allowance, and those who tracked spending in an app saved the most." },
    { id: "play-based", title: "Play-Based Learning and Social Skills of Preschool Children",
      type: "Faculty Research", year: "2014", department: "Preschool",
      authors: "Lorenzo, Marissa C.", keywords: "Play-based learning; Social skills; Early childhood; Preschool",
      abstract: "Over one school year, children in play-based classes showed greater gains in sharing, turn-taking, and cooperation than children in more structured classes." },
    { id: "bullying-jhs", title: "Awareness of Anti-Bullying Policies Among Junior High School Students",
      type: "Faculty Research", year: "2016", department: "Junior High School",
      authors: "Sibug, Roberto M.; Palo, Grace Ann D.", keywords: "Bullying; Anti-bullying policy; Junior high school; Student welfare",
      abstract: "Most students knew bullying was prohibited but could not name how to report it. After a homeroom campaign, awareness of reporting procedures rose from 38% to 81%." }
  ];

  var D = {};
  LIST.forEach(function (d) {
    d.pdf = PDF;
    d.college = window.ARCH_COLLEGES ? ARCH_COLLEGES.collegeOf(d.department) : "";
    D[d.id] = d;
  });
  window.ARCH_DOCUMENTS = { list: LIST, all: D, get: function (id) { return D[id] || D[PDF]; }, url: function (id) { return "detail.html?doc=" + encodeURIComponent(id); } };
})();
